language: node_js
node_js:
  - "node"
  - "6"
env:
  global:
    - SAUCE_USERNAME=wimpyprogrammer
  matrix:
    - REACT=0.13
    - REACT=0.14
    - REACT=15
    - REACT=16
addons:
  artifacts:
    paths:
    - artifacts/
  sauce_connect: true
before_install:
  - nvm install-latest-npm
before_script:
  - mkdir -p -v artifacts/
script:
  - travis_wait 30 npm run travisci
after_script:
  - find artifacts/ -name "*.log"
  - cat artifacts/sauce_connect.log
cache:
  directories:
    - node_modules
